[2024-07-20 18:55:57,305] - logger: life - level: ERROR - function: combine_speaker_ids - line: 3016
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/controller/audiodetails.py", line 2992, in combine_speaker_ids
    speaker_ids = projects_collection.find_one({'projectname': activeprojectname},
AttributeError: 'dict' object has no attribute 'find_one'
[2024-07-20 18:55:57,808] - logger: life - level: ERROR - function: combine_speaker_ids - line: 3016
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/controller/audiodetails.py", line 2992, in combine_speaker_ids
    speaker_ids = projects_collection.find_one({'projectname': activeprojectname},
AttributeError: 'dict' object has no attribute 'find_one'
[2024-07-20 18:57:25,390] - logger: life - level: ERROR - function: combine_speaker_ids - line: 3016
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/controller/audiodetails.py", line 2992, in combine_speaker_ids
    speaker_ids = projects_collection.find_one({'projectname': activeprojectname},
AttributeError: 'dict' object has no attribute 'find_one'
[2024-07-20 18:59:01,971] - logger: life - level: ERROR - function: combine_speaker_ids - line: 3016
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/controller/audiodetails.py", line 2992, in combine_speaker_ids
    speaker_ids = projects_collection.find_one({'projectname': activeprojectname},
AttributeError: 'dict' object has no attribute 'find_one'
[2024-07-20 19:00:15,774] - logger: life - level: ERROR - function: combine_speaker_ids - line: 3016
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/controller/audiodetails.py", line 2992, in combine_speaker_ids
    speaker_ids = projects_collection.find_one({'projectname': activeprojectname},
AttributeError: 'dict' object has no attribute 'find_one'
[2024-07-20 19:00:26,873] - logger: life - level: ERROR - function: combine_speaker_ids - line: 3016
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/controller/audiodetails.py", line 2992, in combine_speaker_ids
    speaker_ids = projects_collection.find_one({'projectname': activeprojectname},
AttributeError: 'dict' object has no attribute 'find_one'
[2024-07-20 19:09:10,478] - logger: life - level: ERROR - function: progressReportAdmin - line: 952
An error occurred: local variable 'speaker_id' referenced before assignment
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/routes.py", line 841, in progressReportAdmin
    print("second speaker_id:",speaker_id)
UnboundLocalError: local variable 'speaker_id' referenced before assignment

[2024-07-20 19:09:10,493] - logger: life - level: ERROR - function: progressReportAdmin - line: 952
An error occurred: local variable 'speaker_id' referenced before assignment
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/routes.py", line 841, in progressReportAdmin
    print("second speaker_id:",speaker_id)
UnboundLocalError: local variable 'speaker_id' referenced before assignment

[2024-07-20 19:09:12,020] - logger: life - level: ERROR - function: progressReportAdmin - line: 952
An error occurred: local variable 'speaker_id' referenced before assignment
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/routes.py", line 841, in progressReportAdmin
    print("second speaker_id:",speaker_id)
UnboundLocalError: local variable 'speaker_id' referenced before assignment

[2024-07-20 19:09:12,905] - logger: life - level: ERROR - function: progressReportAdmin - line: 952
An error occurred: local variable 'speaker_id' referenced before assignment
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/routes.py", line 841, in progressReportAdmin
    print("second speaker_id:",speaker_id)
UnboundLocalError: local variable 'speaker_id' referenced before assignment

[2024-07-20 19:10:23,313] - logger: life - level: ERROR - function: progressReportAdmin - line: 870
An error occurred: name 'project_names_file_wise' is not defined
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/routes.py", line 864, in progressReportAdmin
    project_names_file_wise=project_names_file_wise,
NameError: name 'project_names_file_wise' is not defined

[2024-07-20 19:11:41,722] - logger: life - level: ERROR - function: progressReportAdmin - line: 870
An error occurred: name 'project_names_file_wise' is not defined
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/routes.py", line 864, in progressReportAdmin
    project_names_file_wise=project_names_file_wise,
NameError: name 'project_names_file_wise' is not defined

[2024-07-20 20:13:07,728] - logger: life - level: ERROR - function: progressReportAdmin - line: 961
An error occurred: local variable 'activeprojectform' referenced before assignment
Traceback (most recent call last):
  File "/home/kmi/lifetestapp/app/routes.py", line 859, in progressReportAdmin
    print("activeprojectform : ", activeprojectform)
UnboundLocalError: local variable 'activeprojectform' referenced before assignment

[2024-07-21 08:35:57,464] - logger: life - level: INFO - function: generate_languages_database - line: 102
language Database found!
[2024-07-21 08:35:57,467] - logger: life - level: INFO - function: generate_models_database - line: 55
Models Database found!
[2024-07-21 08:36:00,812] - logger: life - level: INFO - function: generate_languages_database - line: 102
language Database found!
[2024-07-21 08:36:00,813] - logger: life - level: INFO - function: generate_models_database - line: 55
Models Database found!
[2024-07-21 08:36:06,483] - logger: life - level: INFO - function: generate_languages_database - line: 102
language Database found!
[2024-07-21 08:36:06,484] - logger: life - level: INFO - function: generate_models_database - line: 55
Models Database found!
[2024-07-21 12:51:40,063] - logger: life - level: INFO - function: generate_languages_database - line: 102
language Database found!
[2024-07-21 12:51:40,064] - logger: life - level: INFO - function: generate_models_database - line: 55
Models Database found!
[2024-07-21 12:51:42,220] - logger: life - level: INFO - function: generate_languages_database - line: 102
language Database found!
[2024-07-21 12:51:42,221] - logger: life - level: INFO - function: generate_models_database - line: 55
Models Database found!
[2024-07-21 15:36:30,716] - logger: life - level: INFO - function: generate_languages_database - line: 102
language Database found!
[2024-07-21 15:36:30,717] - logger: life - level: INFO - function: generate_models_database - line: 55
Models Database found!
[2024-07-21 15:36:44,378] - logger: life - level: INFO - function: generate_languages_database - line: 102
language Database found!
[2024-07-21 15:36:44,379] - logger: life - level: INFO - function: generate_models_database - line: 55
Models Database found!
